config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'
  namespace :potepan do
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    root 'home#index'
    resources :categories, only: :show
    resources :orders, only: [:show, :create, :edit, :update]
    resources :line_items, only: :destroy
    resources :products, only: :show do
      collection do
        get :search, to: 'products#search'
      end
    end
    get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
    patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
    get '/cart', to: 'orders#edit'
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    # サイドバー情報取得
    @categories = Spree::Taxonomy.includes(:taxons)
    # FILTER_BY_OPTION
    @colors = Spree::OptionType.find_by(presentation: "Color").option_values
    @sizes = Spree::OptionType.find_by(presentation: "Size").option_values
    # 商品取得
    @taxon = Spree::Taxon.find(params[:id])
    sort_type = params[:sort_type] || "new_to_old"
    @products = Spree::Product.
      on_taxon(@taxon).
      with_price_and_images.
      order_by(sort_type)

    # URLクエリ
    if params[:option_id]
      option_id = params[:option_id]
      @variants = Spree::Variant.
        on_products_with_option_id(@products, option_id).
        with_price_and_images.
        order_by(sort_type)
    end

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/potepan/checkout_controller.rb
class Potepan::CheckoutController < ApplicationController
  before_action :load_order, only: [:edit, :update]
  around_action :lock_order, only: [:edit, :update]
  before_action :set_state_if_present, only: [:edit, :update]
  before_action :ensure_order_not_completed, only: [:edit, :update]
  before_action :ensure_checkout_allowed, only: [:edit, :update]
  before_action :ensure_sufficient_stock_lines, only: [:edit, :update]
  before_action :ensure_valid_state, only: [:edit, :update]
  before_action :associate_user, only: [:edit, :update]
  before_action :setup_for_current_state, only: [:edit, :update]

  rescue_from Spree::Core::GatewayError, with: :rescue_from_spree_gateway_error

  # Updates the order and advances to the next state (when possible.)
  def update
    if update_order
      unless transition_forward
        redirect_on_failure
        return
      end
      if @order.completed?
        redirect_to potepan_order_path(@order)
      else
        send_to_next_state
      end
    else
      render :edit
    end
  end

  private

  def update_order
    Spree::OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
  end

  def update_params
    if update_params = massaged_params[:order]
      update_params.permit(permitted_checkout_attributes)
    else
      # We currently allow update requests without any parameters in them.
      {}
    end
  end

  def massaged_params
    massaged_params = params.deep_dup
    move_payment_source_into_payments_attributes(massaged_params)
    set_payment_parameters_amount(massaged_params, @order)
    massaged_params
  end

  def move_and_modifay_payment_source_into_payments_attributes(params)
    return params if params[:payment_source].blank?
    payment_params = params[:order] &&
                     params[:order][:payments_attributes] &&
                     params[:order][:payments_attributes].first
    return params if payment_params.blank?
    payment_method_id = payment_params[:payment_method_id]
    return params if payment_method_id.blank?
    expiry_all = params[:payment_source][payment_method_id][:expiry]
    expiry_month = expiry_all["value(2i)"]
    expiry_year = expiry_all["value(1i)"]
    expiry_month = "0#{expiry_month}" if expiry_month.to_i < 10
    expiry = "#{expiry_month} / #{expiry_year}"
    params[:payment_source][payment_method_id][:expiry] = expiry
    source_params = params[:payment_source][payment_method_id]
    return params if source_params.blank?
    payment_params[:source_attributes] = source_params
    params.delete(:payment_source)
    params
  end

  def transition_forward
    if @order.can_complete?
      @order.complete
    else
      @order.next
      @order.next if @order.state == "delivery"
    end
  end

  def redirect_on_failure
    flash[:error] = @order.errors.full_messages.join("\n")
    redirect_to potepan_checkout_state_path(@order.state)
  end

  def send_to_next_state
    redirect_to potepan_checkout_state_path(@order.state)
  end

  def load_order
    @order = current_order
    redirect_to(potepan_root_path) && return unless @order
  end

  def set_state_if_present
    if params[:state]
      redirect_to potepan_checkout_state_path(@order.state) if @order.can_go_to_state?(params[:state])
      @order.state = params[:state]
    end
  end

  def ensure_order_not_completed
    redirect_to potepan_cart_path if @order.completed?
  end

  def ensure_checkout_allowed
    unless @order.checkout_allowed?
      redirect_to potepan_cart_path
    end
  end

  def ensure_sufficient_stock_lines
    if @order.insufficient_stock_lines.present?
      out_of_stock_items = @order.insufficient_stock_lines.collect(&:name).to_sentence
      flash[:error] = t('spree.inventory_error_flash_for_insufficient_quantity', names: out_of_stock_items)
      redirect_to potepan_cart_path
    end
  end

  def ensure_valid_state
    if (params[:state] && !@order.has_checkout_step?(params[:state])) ||
      (!params[:state] && !@order.has_checkout_step?(@order.state))
      @order.state = 'cart'
      redirect_to potepan_checkout_state_path(@order.checkout_steps.first)
    end
  end

  def setup_for_current_state
    method_name = :"before_#{@order.state}"
    send(method_name) if respond_to?(method_name, true)
  end

  def before_address
    @order.assign_default_user_addresses
    # If the user has a default address, the previous method call takes care
    # of setting that; but if he doesn't, we need to build an empty one here
    default = { country_id: Spree::Country.find_by(name: "Japan").id }
    @order.build_bill_address(default) unless @order.bill_address
    @order.build_ship_address(default) if @order.checkout_steps.include?('delivery') && !@order.ship_address
  end

  def before_payment
    if @order.checkout_steps.include? "delivery"
      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
      @differentiator.missing.each do |variant, quantity|
        @order.contents.remove(variant, quantity)
      end
    end
    @payment_method_id = @order.available_payment_methods.first.id
  end

  def rescue_from_spree_gateway_error(exception)
    flash.now[:error] = t('spree.spree_gateway_error_flash_for_checkout')
    @order.errors.add(:base, exception.message)
    redirect_to potepan_checkout_state_path("payment")
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAXIMUM_NUMBER_OF_NEW_RELEASED_PRODUCTS = 8

  def index
    @new_products = Spree::Product.
      where("available_on > ?", 1.month.ago).
      order(available_on: :desc).
      limit(MAXIMUM_NUMBER_OF_NEW_RELEASED_PRODUCTS)
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  before_action :assign_order

  def destroy
    @line_item = Spree::LineItem.find(params[:id])
    @order.contents.remove_line_item(@line_item)
    @order.reload.line_items.present?
  end

  private

  def assign_order
    @order = current_order
    redirect_to(potepan_root_path) && return unless @order
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  before_action :store_guest_token
  before_action :assign_order, only: :update

  # Adds a new item to the order (creating a new order if none already exists)
  def create
    @order = current_order(create_order_if_necessary: true)
    variant = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1
    # 2,147,483,647 is crazy. See issue https://github.com/spree/spree/issues/2695.
    if !quantity.between?(1, 2_147_483_647)
      @order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end
    begin
      @line_item = @order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => error
      @order.errors.add(:base, error.record.errors.full_messages.join(", "))
    end
    if @order.errors.any?
      flash[:error] = @order.errors.full_messages.join(", ")
      redirect_back(fallback_location: potepan_root_path) and return
      return
    else
      redirect_to potepan_cart_path
    end
  end

  # Shows the current incomplete order from the session
  def edit
    @order = Spree::Order.incomplete.find_or_initialize_by(
      guest_token: cookies.signed[:guest_token]
    )
  end

  def update
    if @order.contents.update_cart(order_params)
      if params.key?(:checkout) && @order.cart?
        @order.next
      end
      if params.key?(:checkout)
        redirect_to potepan_checkout_state_path(@order.checkout_steps.first) and return
      end
    end
    redirect_to potepan_cart_path
  end

  private

  def store_guest_token
    cookies.permanent.signed[:guest_token] = params[:token] if params[:token]
  end

  def order_params
    if params[:order]
      params[:order].permit(*permitted_order_attributes)
    else
      {}
    end
  end

  def assign_order
    @order = current_order
    unless @order
      flash[:error] = t('spree.order_not_found')
      redirect_to(root_path) and return
    end
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAXIMUM_NUMBER_OF_RELATED_PRODUCTS = 4

  def show
    @product = Spree::Product.find(params[:id])
    @images = @product.images
    @related_products = Spree::Product.related_products(@product).limit(MAXIMUM_NUMBER_OF_RELATED_PRODUCTS)
  end

  def search
    @keywords = params[:keywords]

    if @keywords.blank?
      @products = []
    else
      @products = Spree::Product.
        where("spree_products.name LIKE :keyword", keyword: "%#{ActiveRecord::Base.sanitize_sql_like(@keywords)}%").
        or(Spree::Product.
        where("spree_products.description LIKE :keyword", keyword: "%#{ActiveRecord::Base.sanitize_sql_like(@keywords)}%")).
        includes(master: [:default_price, :images])
    end
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/potepan/categories_helper.rb
module Potepan
  module CategoriesHelper
    def variants_count_on_option(option:, taxon:)
      Spree::Variant.
        joins(:option_values).
        where(product_id: taxon.products.ids).
        where("spree_option_values.id": option.id).
        count
    end
  end
end

app/helpers/potepan/checkout_helper.rb
module Potepan
  module CheckoutHelper
    def select_render(state)
      if state == "address"
        return render('potepan/checkout/address') # rubocop: disable Style/RedundantReturn
      elsif state == "payment"
        return render('potepan/checkout/payment') # rubocop: disable Style/RedundantReturn
      elsif state == "confirm"
        return render('potepan/checkout/confirm') # rubocop: disable Style/RedundantReturn
      end
    end
  end
end

app/helpers/potepan/orders_helper.rb
module Potepan
  module OrdersHelper
    def line_item_name(line_item)
      option_value = line_item.variant.options_text
      if line_item.variant.is_master?
        line_item.name
      else
        "#{line_item.name} (#{option_value})"
      end
    end
  end
end

app/helpers/potepan/products_helper.rb
require 'carmen'

module Potepan
  module ProductsHelper
    include Spree::ProductsHelper

    def select_box_of_variant(product)
      if product.has_variants?
        select_tag(:variant_id, options_from_collection_for_select(product.variants_and_option_values_for, :id, :options_text))
      else
        hidden_field_tag(:variant_id, product.master.id)
      end
    end
  end
end

app/views/potepan/categories/_left_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">商品カテゴリー</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% categories.each_with_index do |category, i| %>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#category-<%= i %>">
                <%= category.name %>
                <i class="fa fa-plus"></i>
              </a>
              <ul id="category-<%= i %>" class="collapse collapseItem">
                <% category.root.leaves.each do |leaf| %>
                  <li>
                    <%= link_to potepan_category_path(leaf.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i>
                      <%= leaf.name %>
                      <span><%= "(#{leaf.all_products.count})" %></span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">色から探す</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <%= render partial: 'option', collection: colors, as: :option, locals: {taxon: taxon} %>
      </ul>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <%= render partial: 'option', collection: sizes, as: :option, locals: {taxon: taxon} %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_light_section_page_header.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= page_title.upcase %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_index_path %>
          </li>
          <li>
            <%= link_to "Shop", "#" %>
          </li>
          <li class="active">
            <%= page_title %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_option.html.erb
<li>
  <%= link_to potepan_category_path(taxon.id, option_id: option.id) do %>
    <%= option.name %><span>(<%= variants_count_on_option(option: option, taxon: taxon) %>)</span>
  <% end %>
</li>

app/views/potepan/categories/_products_list.html.erb
<div class="row">
  <% products.each do |product| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag product.display_image.attachment(:product) %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= product.name %></h5>
            <h3><%= product.display_price %></h3>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_sort_dropdown_list.html.erb
<%= form_tag(request.path, method: :get, enforce_utf8: false) do %>
  <%= select_tag :sort_type, options_for_select([
    ["新着順", 'new_to_old'],
    ["安い順", 'price_asc'],
    ["高い順", 'price_desc'],
    ["古い順", 'old_to_new']],
    selected: params[:sort_type] || 'new_to_old'),
    { class: "select-drop", onchange: "this.form.submit()" } %>
  <%= hidden_field_tag(:option_id, params[:option_id]) unless params[:option_id].nil? %>
<% end %>

app/views/potepan/categories/_variants_list.html.erb
<div class="row">
  <% variants.each do |variant| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(variant.product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag variant.display_image.attachment(:product) %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= variant.product.name %></h5>
            <h3><%= variant.display_price %></h3>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<%= render 'light_section_page_header', page_title: @taxon.name %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render 'left_sidebar', categories: @categories, colors: @colors, sizes: @sizes, taxon: @taxon %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <%= render 'sort_dropdown_list' %>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div id="productsList">
          <% if @variants %>
            <%= render 'variants_list', variants: @variants %>
          <% else %>
            <%= render 'products_list', products: @products %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/show.js.erb
$('#productsList').html("<%= escape_javascript(render partial: 'products_list',
                                             locals: { products: @products }) %>");
$('.page-title').html("<h2><%= @taxon.name %></h2>");
$('title').html("<%= @taxon.name %>");